import { GatewayKey } from '@src/common/types/gateway.types';
import { Money } from '../value-objects/money.value-object';
import { PaymentStatus } from './payment-status.enum';

/**
 * Unified representation of a payment across all gateways.
 *
 * This entity normalizes payment data from different providers (Stripe, PayPal)
 * into a consistent structure that can be used throughout your application.
 *
 * @example
 * ```typescript
 * const payment: Payment = {
 *   id: 'pay_abc123',
 *   gateway: 'stripe',
 *   gatewayPaymentId: 'pi_1234567890',
 *   amount: { currency: 'USD', amount: 1000 },
 *   status: PaymentStatus.Captured,
 *   createdAt: new Date('2026-01-01'),
 *   updatedAt: new Date('2026-01-01'),
 *   metadata: { orderId: 'order_123' }
 * };
 * ```
 */
export interface Payment {
  /**
   * Internal PaymentKit identifier.
   * Generated by PaymentKit for tracking purposes.
   *
   * @example 'pay_abc123'
   */
  id: string;

  /**
   * The payment gateway that processed this payment.
   *
   * @example 'stripe'
   * @example 'paypal'
   */
  gateway: GatewayKey;

  /**
   * Provider-specific payment identifier.
   *
   * - Stripe: PaymentIntent ID (e.g., 'pi_1234567890')
   * - PayPal: Capture ID (e.g., '3C679366H7976362F')
   *
   * @example 'pi_1234567890' // Stripe
   * @example '3C679366H7976362F' // PayPal
   */
  gatewayPaymentId: string;

  /**
   * Payment amount in minor units (cents, yen, etc.).
   *
   * @example { currency: 'USD', amount: 1000 } // $10.00
   * @example { currency: 'JPY', amount: 1000 } // ¥1,000
   */
  amount: Money;

  /**
   * Current status of the payment in its lifecycle.
   *
   * @see PaymentStatus
   */
  status: PaymentStatus;

  /**
   * Timestamp when the payment was created.
   */
  createdAt: Date;

  /**
   * Timestamp when the payment was last updated.
   */
  updatedAt: Date;

  /**
   * Arbitrary user-defined metadata attached to the payment.
   * Can be used to store application-specific information.
   *
   * @example { orderId: 'order_123', customerId: 'cust_456' }
   */
  metadata?: Record<string, unknown>;
}
